version: '3.8'

services:
  gbh-books-api:
    build: ./gbh-books-api
    container_name: gbh-books-api
    ports:
      - "8000:8000"
    volumes:
      - ./gbh-books-api:/app
    environment:
      - DATABASE_URL=sqlite:///./gbh-books.db

  gbh-books-ui:
    build:
      context: ./gbh-books-ui
      args:
        - REACT_APP_API_BASE_URL=http://localhost:8000
    container_name: gbh-books-ui
    ports:
      - "3000:3000"
    volumes:
      - ./gbh-books-ui:/app
      - /app/node_modules
    depends_on:
      - gbh-books-api

