"""Add relationship between Book and Page

Revision ID: 16e147416a3c
Revises: fba39da1f4ba
Create Date: 2024-10-24 12:20:47.745865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e147416a3c'
down_revision = 'fba39da1f4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
