"""Create books and pages tables

Revision ID: c7cff525ee99
Revises: 16e147416a3c
Create Date: 2024-10-25 14:04:37.632826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cff525ee99'
down_revision = '16e147416a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
